name: Go

on: [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'ximiximi1-patch-1'

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: env GOOS=windows GOARCH=amd64 go build -v -o ./build/chisel.exe

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./build/chisel.exe
